name: yes_parser
description: 
  Dart implementation of the YES scriplet standard.
  YES is a meta scriptlet standard whose elements and meaning are determined
  by the programmer. They can be extended further with attributes which
  allow end-users to make their additions to those elements.
  This library parses documents using the YES spec and delivers
  the result as elements of type Global, Standard, Attribute, and Comment.
  The programmer can use the KeyVal args passed into each element to
  provide external functionality to their own software easily and quickly
  at no cost to readability or flexibility. It is a format for everyone.

version: 1.0.1
repository: https://github.com/TheMaverickProgrammer/dart_yes_parser

environment:
  sdk: ^3.3.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
