name: yes_parser
description: Dart implementation of the YES scriplet standard
version: 1.0.0
repository: https://github.com/TheMaverickProgrammer/dart_yes_parser

environment:
  sdk: ^3.3.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
